### ISSUE TITLE
Unused bundlePath in kill.c

### ISSUE THREAD

**Issue by wking** [projectatomic/bwrap-oci#9]
We should be able to drop [`bundlePath` from `kill.c`][1].  This may involve teaching `read_container_status_file` to accept `NULL` for unneeded arguments, but should be fairly straightforward.  I can work up a PR on Monday, but wanted to file this so I don't forget.

[1]: https://github.com/projectatomic/bwrap-oci/blob/f896a3971e9b7f4dade544f0342eafc85acf2879/kill.c#L31

**Comment by marcosps** [comment]
As the PR was accepted, can this issue be closed?
